// Code generated by protoc-gen-gogrpc-permissions. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	authz "github.com/hxtk/yggdrasil/common/authz"
	v1alpha1 "github.com/hxtk/yggdrasil/common/authz/v1alpha1"
)

var resourcePermissions_ALL = map[string]*v1alpha1.PermissionsRule{
	"/yggdrasil.toolproxy.v1.ToolProxy/ListCommands": {
		ResourceType: "commands",
		Permission:   "list",
	},
	"/yggdrasil.toolproxy.v1.ToolProxy/CreateCommand": {
		ResourceType: "commands",
		Permission:   "create",
	},
	"/yggdrasil.toolproxy.v1.ToolProxy/GetCommand": {
		ResourceType: "commands",
		Permission:   "read",
	},
	"/yggdrasil.toolproxy.v1.ToolProxy/UpdateCommand": {
		ResourceType: "commands",
		Permission:   "edit",
	},
	"/yggdrasil.toolproxy.v1.ToolProxy/RunCommand": {
		ResourceType: "commands",
		Permission:   "execute",
	},
	"/yggdrasil.toolproxy.v1.ToolProxy/DeleteCommand": {
		ResourceType: "commands",
		Permission:   "delete",
	},
}

var resourcePermissions_ToolProxy = map[string]*v1alpha1.PermissionsRule{
	"/yggdrasil.toolproxy.v1.ToolProxy/ListCommands": {
		ResourceType: "commands",
		Permission:   "list",
	},
	"/yggdrasil.toolproxy.v1.ToolProxy/CreateCommand": {
		ResourceType: "commands",
		Permission:   "create",
	},
	"/yggdrasil.toolproxy.v1.ToolProxy/GetCommand": {
		ResourceType: "commands",
		Permission:   "read",
	},
	"/yggdrasil.toolproxy.v1.ToolProxy/UpdateCommand": {
		ResourceType: "commands",
		Permission:   "edit",
	},
	"/yggdrasil.toolproxy.v1.ToolProxy/RunCommand": {
		ResourceType: "commands",
		Permission:   "execute",
	},
	"/yggdrasil.toolproxy.v1.ToolProxy/DeleteCommand": {
		ResourceType: "commands",
		Permission:   "delete",
	},
}

func Permissions(method string) (*v1alpha1.PermissionsRule, error) {
	if res, ok := resourcePermissions_ALL[method]; ok {
		return res, nil
	}
	return nil, fmt.Errorf("no permissions found for method %s", method)
}

// RegisterToolProxyPermissions registers the static permissions of ToolProxy to reg.
func RegisterToolProxyPermissions(reg authz.Registrar) {
	for k, v := range resourcePermissions_ToolProxy {
		reg.RegisterPermission(k, v)
	}
}
